  spring:
    application:
               name: Student-Managment

    datasource:
      url: jdbc:mysql://student.ccdqo46ustg4.us-east-1.rds.amazonaws.com:3306/userDB?useSSL=false
      username: root
      password: ${DBPASSWORD}

    jpa:
      show-sql: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  server:
    port: 5000